//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BobEProcure_Packages
    {
        public int Id { get; set; }
        public string PQId { get; set; }
        public string Ref { get; set; }
        public string Title { get; set; }
        public string Type { get; set; }
        public string Country { get; set; }
        public string Approver { get; set; }
        public Nullable<int> Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public Nullable<System.DateTime> DraftDate { get; set; }
        public string ProjectInfo { get; set; }
        public string LocNumber { get; set; }
        public Nullable<decimal> PrimaryJvPercentage { get; set; }
        public Nullable<decimal> SecondaryJvPercentage { get; set; }
        public Nullable<decimal> LocAmount { get; set; }
        public string TypeOfPackage { get; set; }
        public Nullable<int> SerialNo { get; set; }
        public Nullable<int> NoOfPackage { get; set; }
        public Nullable<decimal> PackageDuration { get; set; }
        public Nullable<int> LeadMinimumShare { get; set; }
        public Nullable<int> JvMinShare { get; set; }
        public string PackageId { get; set; }
        public string PackageName { get; set; }
        public Nullable<decimal> PackageValue { get; set; }
        public Nullable<int> Index { get; set; }
        public string PackageDisplayId { get; set; }
        public Nullable<decimal> EstimateValue { get; set; }
        public Nullable<decimal> AverageRequirement { get; set; }
        public Nullable<decimal> CashFlowRequirement { get; set; }
        public string PQNo { get; set; }
    }
}
