//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BobEProcure_Status
    {
        public int Id { get; set; }
        public string PQSupplierId { get; set; }
        public string PQId { get; set; }
        public string SupplierId { get; set; }
        public Nullable<int> ParticipationStatus { get; set; }
        public Nullable<System.DateTime> ParticipationDate { get; set; }
        public Nullable<int> ENCStatus { get; set; }
        public string SuppPQSubmId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> DraftStatus { get; set; }
        public Nullable<System.DateTime> SubmisionDate { get; set; }
        public string ApplicantType { get; set; }
        public string SupplierApprDtlId { get; set; }
        public Nullable<int> PreQualificationStatus { get; set; }
        public string Comments { get; set; }
        public string PQNo { get; set; }
    }
}
