//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponentHashtable
    {
        public Nullable<int> CheckSumValue { get; set; }
        public string work_order { get; set; }
        public string description { get; set; }
        public string InputterID { get; set; }
        public string QualityAssurerID { get; set; }
        public string department { get; set; }
        public string project { get; set; }
        public string dfid_role { get; set; }
        public string admin_bud_approver { get; set; }
        public string funding_mechanism { get; set; }
        public string op_status { get; set; }
        public string benefitting_country { get; set; }
        public System.DateTime last_update { get; set; }
        public string UserID { get; set; }
    }
}
