//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponentMaster1
    {
        public int Identity { get; set; }
        public string Change_Status { get; set; }
        public string ComponentID { get; set; }
        public string ComponentDescription { get; set; }
        public string BudgetCentreID { get; set; }
        public string ProjectID { get; set; }
        public string AdminApprover { get; set; }
        public string FundingMechanism { get; set; }
        public string OperationalStatus { get; set; }
        public string BenefittingCountry { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string UserID { get; set; }
        public string Approved { get; set; }
        public string FundingArrangementValue { get; set; }
        public string PartnerOrganisationValue { get; set; }
    }
}
