//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DateHashTable
    {
        public Nullable<int> CheckSumValue { get; set; }
        public string project { get; set; }
        public System.DateTime created_date { get; set; }
        public System.DateTime date_from { get; set; }
        public System.DateTime date_to { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<System.DateTime> actual_start { get; set; }
        public Nullable<System.DateTime> promp_compl { get; set; }
        public Nullable<System.DateTime> ies_date { get; set; }
        public System.DateTime last_update { get; set; }
        public string User_ID { get; set; }
    }
}
