//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evaluation1
    {
        public int Identity { get; set; }
        public string Change_Status { get; set; }
        public int EvaluationID { get; set; }
        public string ProjectID { get; set; }
        public string EvaluationTypeID { get; set; }
        public string IfOther { get; set; }
        public string ManagementOfEvaluation { get; set; }
        public Nullable<decimal> EstimatedBudget { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string AdditionalInfo { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string UserID { get; set; }
    }
}
