//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Finacle_Contracts
    {
        public int Id { get; set; }
        public string CIF { get; set; }
        public string ContractId { get; set; }
        public string ContractorName { get; set; }
        public Nullable<decimal> ContractValue { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public string Prefix { get; set; }
        public string Suffix { get; set; }
        public string CGS_ID { get; set; }
    }
}
