//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Finacle_RepaymentSchedule
    {
        public int Id { get; set; }
        public string FORACID { get; set; }
        public string LimitPrefix { get; set; }
        public string AccountName { get; set; }
        public Nullable<System.DateTime> FlowStart { get; set; }
        public string FlowId { get; set; }
        public Nullable<decimal> FlowAmount { get; set; }
        public string Currency { get; set; }
    }
}
