//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Finacle_PrincipalDue
    {
        public int Id { get; set; }
        public string AccountId { get; set; }
        public string DemandType { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Frequency { get; set; }
        public Nullable<decimal> DueAmount { get; set; }
        public Nullable<System.DateTime> RunDate { get; set; }
    }
}
