//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Finacle_AMDemands
    {
        public int Id { get; set; }
        public string FORACID { get; set; }
        public string AccountName { get; set; }
        public string DemandFlowId { get; set; }
        public Nullable<decimal> DemandAmount { get; set; }
        public Nullable<System.DateTime> LastAdjustmentDate { get; set; }
        public Nullable<decimal> TotalAdjustmentAmount { get; set; }
        public Nullable<System.DateTime> DemandEffectiveDate { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
