//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Finacle_LocFinancials
    {
        public int Id { get; set; }
        public string LimitPrefix { get; set; }
        public string FORACID { get; set; }
        public string AccountName { get; set; }
        public Nullable<decimal> LoanOutstanding { get; set; }
        public Nullable<decimal> TotalDisbursed { get; set; }
        public Nullable<decimal> PrincipalDemand { get; set; }
        public Nullable<decimal> PrincipalCollection { get; set; }
        public Nullable<decimal> PrincipalOverdue { get; set; }
        public Nullable<decimal> InterestDemand { get; set; }
        public Nullable<decimal> InterestCollection { get; set; }
        public Nullable<decimal> InterestOverdue { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
    }
}
