//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Finacle_Disbursement
    {
        public int Id { get; set; }
        public string ACID { get; set; }
        public string LimitPrefix { get; set; }
        public string LimitB2KID { get; set; }
        public string FORACID { get; set; }
        public string AccountName { get; set; }
        public Nullable<decimal> SanctionLimit { get; set; }
        public Nullable<decimal> DisbAmount { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<System.DateTime> DisDate { get; set; }
        public string DisbSerialNo { get; set; }
    }
}
