//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Finacle_LocDetails
    {
        public int Id { get; set; }
        public string LimitB2KID { get; set; }
        public string AccountName { get; set; }
        public string FreeText { get; set; }
        public string LimitPrefix { get; set; }
        public string LimitSuffix { get; set; }
        public Nullable<decimal> SanctionAmount { get; set; }
        public string CIF { get; set; }
    }
}
