//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Finacle_LocTransactions
    {
        public int Id { get; set; }
        public string FORACID { get; set; }
        public string CIFID { get; set; }
        public string DemandFlow { get; set; }
        public string DeleteFlag { get; set; }
        public Nullable<decimal> DemandAmount { get; set; }
        public Nullable<System.DateTime> LastAdjustmentDate { get; set; }
        public Nullable<decimal> TotalAdjustedAmt { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CurrencyCode { get; set; }
        public string Prefix { get; set; }
    }
}
