//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Finacle_CGS
    {
        public int Id { get; set; }
        public string FORACID { get; set; }
        public string AccountName { get; set; }
        public Nullable<System.DateTime> AccountOpenDate { get; set; }
        public Nullable<decimal> ClearBalanceAmount { get; set; }
        public string AccountMgr { get; set; }
        public string CIF { get; set; }
        public string SchemeCode { get; set; }
        public string Currency { get; set; }
    }
}
