//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeoCode
    {
        public long GeoID { get; set; }
        public string ProjectID { get; set; }
        public string LocationPoint { get; set; }
        public string CountryCodeID { get; set; }
        public string Administrative { get; set; }
        public double Longitude { get; set; }
        public double Latitude { get; set; }
        public int PrecisionID { get; set; }
        public string LocationTypeID { get; set; }
        public bool Confirmed { get; set; }
        public int Deleted { get; set; }
        public Nullable<double> Percentage { get; set; }
        public Nullable<bool> CMP { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string UserID { get; set; }
        public System.DateTime LastUpdated { get; set; }
    
        public virtual CountryCode CountryCode { get; set; }
        public virtual LocationType LocationType { get; set; }
        public virtual Precision Precision { get; set; }
        public virtual ProjectMaster ProjectMaster { get; set; }
        public virtual ProjectMaster ProjectMaster1 { get; set; }
    }
}
