//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutputIndicatorMilestone
    {
        public int ID { get; set; }
        public Nullable<int> OutputIndicatorID { get; set; }
        public Nullable<int> MilestoneID { get; set; }
        public Nullable<System.DateTime> From { get; set; }
        public Nullable<System.DateTime> To { get; set; }
        public string Planned { get; set; }
        public string Change { get; set; }
        public string Achieved { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string UserID { get; set; }
    
        public virtual OutputIndicator OutputIndicator { get; set; }
    }
}
