//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutputIndicator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OutputIndicator()
        {
            this.OutputIndicatorMilestones = new HashSet<OutputIndicatorMilestone>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ProjectOutputID { get; set; }
        public Nullable<int> OutputIndicatorID { get; set; }
        public string IndicatorDescription { get; set; }
        public string Source { get; set; }
        public string Units { get; set; }
        public string Baseline { get; set; }
        public Nullable<System.DateTime> BaselineDate { get; set; }
        public string Target { get; set; }
        public Nullable<System.DateTime> TargetDate { get; set; }
        public string TargetAchieved { get; set; }
        public string IsDRF { get; set; }
        public string IsCHR { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string UserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutputIndicatorMilestone> OutputIndicatorMilestones { get; set; }
        public virtual ProjectOutput ProjectOutput { get; set; }
    }
}
