//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectInfoTable
    {
        public Nullable<int> CheckSumValue { get; set; }
        public string project { get; set; }
        public string ovis { get; set; }
        public string team_marker { get; set; }
        public string approval_risk { get; set; }
        public string specific_conditions { get; set; }
        public string GenderEquality { get; set; }
        public string HIVAIDS { get; set; }
        public System.DateTime last_update { get; set; }
        public string User_ID { get; set; }
    }
}
