//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectTeamHash
    {
        public Nullable<int> CheckSumValue { get; set; }
        public string ProjectID { get; set; }
        public string name { get; set; }
        public string role { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> date_from_fx { get; set; }
        public Nullable<System.DateTime> date_to_fx { get; set; }
        public Nullable<System.DateTime> last_update { get; set; }
        public string User_ID { get; set; }
    }
}
