//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectMarker
    {
        public int Identity { get; set; }
        public string ChangeStatus { get; set; }
        public string ProjectID { get; set; }
        public string GenderEquality { get; set; }
        public string HIVAIDS { get; set; }
        public string Biodiversity { get; set; }
        public string Mitigation { get; set; }
        public string Adaptation { get; set; }
        public string Desertification { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string UserID { get; set; }
    }
}
