//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectOutput
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectOutput()
        {
            this.OutputIndicators = new HashSet<OutputIndicator>();
        }
    
        public int ID { get; set; }
        public string ProjectID { get; set; }
        public Nullable<int> OutputID { get; set; }
        public string ProjectOutputDescription { get; set; }
        public string Assumption { get; set; }
        public Nullable<int> ImpactWeightingPercentage { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string UserID { get; set; }
        public string Risk { get; set; }
    
        public virtual ProjectMaster ProjectMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutputIndicator> OutputIndicators { get; set; }
    }
}
