//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class report_Project
    {
        public string Code { get; set; }
        public string ProjectName { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public Nullable<double> Progress { get; set; }
        public Nullable<double> FinancialProgress { get; set; }
        public decimal ProjectValue { get; set; }
        public Nullable<System.DateTime> ProjectStart { get; set; }
        public Nullable<System.DateTime> ProjectEnd { get; set; }
        public string EstimatedDuration { get; set; }
        public string Sector { get; set; }
        public string SubSectorName { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> DisbursedAmount { get; set; }
        public Nullable<int> LOCCount { get; set; }
        public string PqNo { get; set; }
        public string PqId { get; set; }
        public string PQ_Desc { get; set; }
        public Nullable<decimal> PQ_Loc_Amount { get; set; }
        public Nullable<int> PQ_Package_Count { get; set; }
    }
}
