//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewMaster1
    {
        public string ProjectID { get; set; }
        public int ReviewID { get; set; }
        public string ReviewType { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public Nullable<System.DateTime> DeferralDate { get; set; }
        public string RiskScore { get; set; }
        public string Status { get; set; }
        public string Approved { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string UserID { get; set; }
        public string StageID { get; set; }
        public string ApproveComment { get; set; }
        public string Approver { get; set; }
        public string SubmissionComment { get; set; }
        public string Requester { get; set; }
        public Nullable<decimal> ReviewScore { get; set; }
        public string Change_Status { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
    }
}
