//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReviewMaster()
        {
            this.ReviewDocuments = new HashSet<ReviewDocument>();
            this.ReviewOutputs = new HashSet<ReviewOutput>();
        }
    
        public string ProjectID { get; set; }
        public int ReviewID { get; set; }
        public string ReviewType { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public Nullable<System.DateTime> DeferralDate { get; set; }
        public string RiskScore { get; set; }
        public string Status { get; set; }
        public string Approved { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string UserID { get; set; }
        public string Approver { get; set; }
        public string Requester { get; set; }
        public string StageID { get; set; }
        public string SubmissionComment { get; set; }
        public string ApproveComment { get; set; }
        public Nullable<decimal> ReviewScore { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
    
        public virtual ProjectMaster ProjectMaster { get; set; }
        public virtual ReviewARScore ReviewARScore { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReviewDocument> ReviewDocuments { get; set; }
        public virtual Risk Risk { get; set; }
        public virtual ReviewStage ReviewStage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReviewOutput> ReviewOutputs { get; set; }
        public virtual ReviewPCRScore ReviewPCRScore { get; set; }
    }
}
