//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_EmailRules
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_EmailRules()
        {
            this.TBL_RuleTransactions = new HashSet<TBL_RuleTransactions>();
        }
    
        public int Id { get; set; }
        public Nullable<int> OffMonth { get; set; }
        public Nullable<int> OffWeek { get; set; }
        public Nullable<int> OffDay { get; set; }
        public Nullable<int> FreqMonth { get; set; }
        public Nullable<int> FreqWeek { get; set; }
        public Nullable<int> FreqDay { get; set; }
        public string RuleFor { get; set; }
        public string RuleName { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_RuleTransactions> TBL_RuleTransactions { get; set; }
    }
}
