//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Terms
    {
        public int Id { get; set; }
        public double InterestRate { get; set; }
        public double CommitmentFee { get; set; }
        public double ManagementFee { get; set; }
        public int Tenure { get; set; }
        public int Moratorium { get; set; }
        public double IndianContribution { get; set; }
        public string SpecialConditions { get; set; }
        public string CurrencyCode { get; set; }
        public string Type { get; set; }
        public string ApprovalType { get; set; }
        public double Percentage { get; set; }
        public string LOCClassification { get; set; }
        public string RiskClassification { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string InterestType { get; set; }
    
        public virtual TBL_Users TBL_Users { get; set; }
        public virtual TBL_Users TBL_Users1 { get; set; }
    }
}
