//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Projects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Projects()
        {
            this.TBL_LOC_Project = new HashSet<TBL_LOC_Project>();
            this.TBL_Projects_PQ = new HashSet<TBL_Projects_PQ>();
            this.TBL_StakeHolders = new HashSet<TBL_StakeHolders>();
            this.TBL_Project_Contacts = new HashSet<TBL_Project_Contacts>();
            this.TBL_ProjectLogs = new HashSet<TBL_ProjectLogs>();
            this.TBL_ProjectTimeLines = new HashSet<TBL_ProjectTimeLines>();
            this.TBL_ProjectLocations = new HashSet<TBL_ProjectLocations>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> DPRDate { get; set; }
        public string BaselineData { get; set; }
        public string LocationAddress { get; set; }
        public string LocationCoordinates { get; set; }
        public Nullable<int> Stage { get; set; }
        public Nullable<int> SubSector { get; set; }
        public Nullable<bool> PreQualification { get; set; }
        public string AuthorityName { get; set; }
        public Nullable<double> Progress { get; set; }
        public Nullable<double> FinancialProgress { get; set; }
        public decimal ProjectValue { get; set; }
        public Nullable<System.DateTime> ProjectStart { get; set; }
        public Nullable<System.DateTime> ProjectEnd { get; set; }
        public System.DateTime CrOn { get; set; }
        public Nullable<System.DateTime> ModOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Sector { get; set; }
        public string SubSectorName { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> AddressLat { get; set; }
        public Nullable<decimal> AddressLon { get; set; }
        public Nullable<decimal> DisbursedAmount { get; set; }
        public string Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_LOC_Project> TBL_LOC_Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Projects_PQ> TBL_Projects_PQ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_StakeHolders> TBL_StakeHolders { get; set; }
        public virtual TBL_Status TBL_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Project_Contacts> TBL_Project_Contacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_ProjectLogs> TBL_ProjectLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_ProjectTimeLines> TBL_ProjectTimeLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_ProjectLocations> TBL_ProjectLocations { get; set; }
    }
}
