//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ContractLC
    {
        public int Id { get; set; }
        public int ContractId { get; set; }
        public string LCNumber { get; set; }
        public string Beneficiary { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> OpeningDate { get; set; }
        public string IssuingBank { get; set; }
        public Nullable<System.DateTime> LastDateofShipment { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<decimal> TransferableAmount { get; set; }
        public string LCNote { get; set; }
    
        public virtual TBL_Contracts TBL_Contracts { get; set; }
    }
}
