//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ContractContent
    {
        public int Id { get; set; }
        public int ContractId { get; set; }
        public decimal Value { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public bool isExempt { get; set; }
        public string RevisedRequirement { get; set; }
        public string MEAApprovalRefNo { get; set; }
        public Nullable<System.DateTime> MEAApprovalDate { get; set; }
        public string Remarks { get; set; }
        public string Type { get; set; }
    
        public virtual TBL_Contracts TBL_Contracts { get; set; }
    }
}
