//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ContractResponsibility
    {
        public int Id { get; set; }
        public string Responsiblity { get; set; }
        public string Authority { get; set; }
        public int ContractId { get; set; }
    
        public virtual TBL_Contracts TBL_Contracts { get; set; }
    }
}
