//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_RuleTransactions
    {
        public int Id { get; set; }
        public Nullable<int> RecordId { get; set; }
        public Nullable<int> RuleId { get; set; }
        public System.DateTime NextRunDate { get; set; }
        public System.DateTime TriggerDate { get; set; }
        public Nullable<System.DateTime> LastRunDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual TBL_EmailRules TBL_EmailRules { get; set; }
    }
}
