//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Contacts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Contacts()
        {
            this.TBL_Project_Contacts = new HashSet<TBL_Project_Contacts>();
            this.TBL_Users = new HashSet<TBL_Users>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Landline { get; set; }
        public string Faxno { get; set; }
        public string MobileNumber { get; set; }
        public string Email { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string Organization { get; set; }
        public string Designation { get; set; }
        public Nullable<int> ContactTypeId { get; set; }
        public byte[] ContactImg { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string City { get; set; }
        public string PinCode { get; set; }
        public Nullable<int> CountryId { get; set; }
    
        public virtual TBL_ContactTypes TBL_ContactTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Project_Contacts> TBL_Project_Contacts { get; set; }
        public virtual TBL_Country TBL_Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Users> TBL_Users { get; set; }
    }
}
