//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_LOC_Amendments
    {
        public int Id { get; set; }
        public Nullable<int> LOC_Id { get; set; }
        public System.DateTime AuditDate { get; set; }
        public string AmendedBy { get; set; }
        public Nullable<System.DateTime> AgreementAmendmentDate { get; set; }
        public Nullable<System.DateTime> TerminalDate { get; set; }
        public Nullable<double> IndianContribution { get; set; }
        public Nullable<System.DateTime> MdAppDate { get; set; }
        public Nullable<System.DateTime> DEAAppDate { get; set; }
        public Nullable<System.DateTime> MEAAppDate { get; set; }
        public Nullable<System.DateTime> OfferLetterDate { get; set; }
        public Nullable<double> InterestRate { get; set; }
        public Nullable<double> CommitmentFee { get; set; }
        public Nullable<double> ManagementFee { get; set; }
        public Nullable<System.DateTime> SigningDate { get; set; }
        public string InterestEqualization { get; set; }
        public string Type { get; set; }
        public Nullable<double> Percentage { get; set; }
        public Nullable<int> Tenure { get; set; }
        public Nullable<int> Moratorium { get; set; }
        public string SpecialCondition { get; set; }
        public string OmNumber { get; set; }
        public string LOCPurpose { get; set; }
        public string InterestType { get; set; }
        public string AmendmentNote { get; set; }
        public Nullable<decimal> AmountAllocated { get; set; }
        public string MEA_Type { get; set; }
        public Nullable<double> MEA_Percentage { get; set; }
        public string DEA_Type { get; set; }
        public Nullable<double> DEA_Percentage { get; set; }
    
        public virtual TBL_LOC TBL_LOC { get; set; }
    }
}
