//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Applicants
    {
        public int Id { get; set; }
        public Nullable<int> Status { get; set; }
        public string Name { get; set; }
        public string Organization { get; set; }
        public string SupplierId { get; set; }
        public Nullable<int> PqId { get; set; }
        public string ApplicantNo { get; set; }
    
        public virtual TBL_Projects_PQ TBL_Projects_PQ { get; set; }
    }
}
