//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_EmailSchedule
    {
        public int Id { get; set; }
        public System.DateTime SendDate { get; set; }
        public string RecordType { get; set; }
        public Nullable<int> RecordId { get; set; }
        public string TemplateName { get; set; }
        public bool IsActive { get; set; }
        public string Notes { get; set; }
    }
}
