//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Options
    {
        public int Id { get; set; }
        public int Type { get; set; }
        public string Value { get; set; }
        public Nullable<int> Parent { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string FaIcon { get; set; }
    
        public virtual TBL_Users TBL_Users { get; set; }
        public virtual TBL_Users TBL_Users1 { get; set; }
    }
}
