//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_LOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_LOC()
        {
            this.TBL_LOC_Contract = new HashSet<TBL_LOC_Contract>();
            this.TBL_LOC_Project = new HashSet<TBL_LOC_Project>();
            this.TBL_ContractLocMap = new HashSet<TBL_ContractLocMap>();
            this.TBL_LOC_Amendments = new HashSet<TBL_LOC_Amendments>();
            this.TBL_LocBalance = new HashSet<TBL_LocBalance>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int CountryId { get; set; }
        public Nullable<int> ApprovalBy { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public Nullable<int> AmendmentNumber { get; set; }
        public string OmNumber { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<System.DateTime> TerminalDate { get; set; }
        public Nullable<System.DateTime> MEAAppDate { get; set; }
        public Nullable<System.DateTime> MdAppDate { get; set; }
        public string FileNumber { get; set; }
        public Nullable<System.DateTime> OfferLetterDate { get; set; }
        public string Purpose { get; set; }
        public double InterestRate { get; set; }
        public double CommitmentFee { get; set; }
        public double ManagementFee { get; set; }
        public string InterestEqualization { get; set; }
        public Nullable<int> Tenure { get; set; }
        public Nullable<int> Moratorium { get; set; }
        public Nullable<double> IndianContribution { get; set; }
        public string SpecialCondition { get; set; }
        public Nullable<System.DateTime> GOIDeedDate { get; set; }
        public string LocAccountNo { get; set; }
        public string CrtAccountNo { get; set; }
        public Nullable<System.DateTime> SigningDate { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> AgreementAmendmentDate { get; set; }
        public string Type { get; set; }
        public Nullable<double> Percentage { get; set; }
        public string ApprovalType { get; set; }
        public string LocNumber { get; set; }
        public string Classification { get; set; }
        public Nullable<System.DateTime> DeaDate { get; set; }
        public string VerificationNote { get; set; }
        public string InterestType { get; set; }
        public string MEA_Type { get; set; }
        public Nullable<double> MEA_Percentage { get; set; }
        public string DEA_Type { get; set; }
        public Nullable<double> DEA_Percentage { get; set; }
    
        public virtual TBL_Country TBL_Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_LOC_Contract> TBL_LOC_Contract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_LOC_Project> TBL_LOC_Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_ContractLocMap> TBL_ContractLocMap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_LOC_Amendments> TBL_LOC_Amendments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_LocBalance> TBL_LocBalance { get; set; }
    }
}
