//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Country
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Country()
        {
            this.TBL_LOC = new HashSet<TBL_LOC>();
            this.TBL_Terms_Country = new HashSet<TBL_Terms_Country>();
            this.TBL_Contacts = new HashSet<TBL_Contacts>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string CIF { get; set; }
        public int RegionId { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string RedFlag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_LOC> TBL_LOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Terms_Country> TBL_Terms_Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Contacts> TBL_Contacts { get; set; }
        public virtual TBL_Users TBL_Users { get; set; }
        public virtual TBL_Users TBL_Users1 { get; set; }
        public virtual TBL_Regions TBL_Regions { get; set; }
    }
}
