//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ProjectLocations
    {
        public int Id { get; set; }
        public int SequenceNumber { get; set; }
        public Nullable<int> Deleted { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Color { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string MapType { get; set; }
    
        public virtual TBL_Projects TBL_Projects { get; set; }
    }
}
