//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Users()
        {
            this.TBL_UserRoleMap = new HashSet<TBL_UserRoleMap>();
            this.TBL_Country = new HashSet<TBL_Country>();
            this.TBL_Country1 = new HashSet<TBL_Country>();
            this.TBL_Options = new HashSet<TBL_Options>();
            this.TBL_Options1 = new HashSet<TBL_Options>();
            this.TBL_Terms = new HashSet<TBL_Terms>();
            this.TBL_Terms1 = new HashSet<TBL_Terms>();
            this.TBL_Activity = new HashSet<TBL_Activity>();
            this.TBl_TeamMapping = new HashSet<TBl_TeamMapping>();
            this.TBL_Regions = new HashSet<TBL_Regions>();
            this.TBL_Regions1 = new HashSet<TBL_Regions>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public string EmployeeNo { get; set; }
        public string Department { get; set; }
        public string DisplayName { get; set; }
        public string EmailAddress { get; set; }
        public int ContactId { get; set; }
    
        public virtual TBL_Contacts TBL_Contacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_UserRoleMap> TBL_UserRoleMap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Country> TBL_Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Country> TBL_Country1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Options> TBL_Options { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Options> TBL_Options1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Terms> TBL_Terms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Terms> TBL_Terms1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Activity> TBL_Activity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBl_TeamMapping> TBl_TeamMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Regions> TBL_Regions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Regions> TBL_Regions1 { get; set; }
    }
}
