//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Files
    {
        public int Id { get; set; }
        public string Src { get; set; }
        public string FileFor { get; set; }
        public int RecordId { get; set; }
        public string DisplayName { get; set; }
    }
}
