//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Projects_PQ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Projects_PQ()
        {
            this.TBL_Contracts = new HashSet<TBL_Contracts>();
            this.Tbl_Applicants = new HashSet<Tbl_Applicants>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string PQRefNumber { get; set; }
        public Nullable<System.DateTime> ApplicationStart { get; set; }
        public Nullable<System.DateTime> ApplicationEnd { get; set; }
        public int ProjectId { get; set; }
        public string addendum_refno { get; set; }
        public Nullable<int> pq_status { get; set; }
        public string PqNo { get; set; }
        public string PqId { get; set; }
        public string Ref { get; set; }
        public string Title { get; set; }
        public string Country { get; set; }
        public string LocNumber { get; set; }
        public Nullable<decimal> LocAmount { get; set; }
        public Nullable<int> NoOfPackage { get; set; }
        public Nullable<decimal> ProjectCost { get; set; }
        public string Category { get; set; }
        public Nullable<System.DateTime> PqDocPublishedOn { get; set; }
        public Nullable<System.DateTime> LastSubmissionOn { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ProjectPQSigninDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Contracts> TBL_Contracts { get; set; }
        public virtual TBL_Projects TBL_Projects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Applicants> Tbl_Applicants { get; set; }
    }
}
