//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vAMPAlert
    {
        public string ProjectID { get; set; }
        public string Message { get; set; }
        public string Path { get; set; }
        public string UserID { get; set; }
        public string Severity { get; set; }
    }
}
