//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zDeliveryChain_PreCR1292793
    {
        public int ID { get; set; }
        public string ComponentID { get; set; }
        public int ChainID { get; set; }
        public int ParentID { get; set; }
        public string ParentType { get; set; }
        public int ChildID { get; set; }
        public string ChildType { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string UserID { get; set; }
        public string Status { get; set; }
    }
}
